export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const GET_NOTICE_UPDATES = "GET_NOTICE_UPDATES";
export const GET_SOLICITATION_UPDATES = "GET_SOLICITATION_UPDATES";
export const REQUEST_PENDING = "REQUEST_PENDING";
export const REQUEST_COMPLETED = "REQUEST_COMPLETED";
export const GET_PREFERENCES = "GET_PREFERENCES";
