export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const GET_NOTICE_UPDATES = "GET_NOTICE_UPDATES";
export const GET_SOLICITATION_UPDATES = "GET_SOLICITATION_UPDATES";
export const REQUEST_PENDING = "REQUEST_PENDING";
export const REQUEST_COMPLETED = "REQUEST_COMPLETED";
export const GET_PREFERENCES = "GET_PREFERENCES";

export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const GET_ACTOR = "GET_ACTOR";
export const GET_ACTORS = "GET_ACTORS";
export const GET_ACTOR_METRICS = "GET_ACTOR_METRICS";
export const GET_PSYCHO_METADATA = "GET_PSYCHO_METADATA";
export const CLEAR_CURRENT_ACTOR = "CLEAR_CURRENT_ACTOR";
